const botIncomeMassages = {
    start: /\/start/,
    continue: /\/continue/,
    investing: /\/investing/,
    saving: /\/saving/,
    debt_management: /\/debt_management/,
    retirement_planning: /\/retirement_planning/,
    fin_security: /\/fin_security/,
    tax_planning: /\/tax_planning/,
    fin_insurance: /\/fin_insurance/,
    inheritance_management: /\/inheritance_management/,
    education_of_children: /\/education_of_children/,
    buying_house: /\/buying_house/,
    budgeting: /\/budgeting/,
    financial_literacy: /\/financial_literacy/,
    fin_goals: /\/fin_goals/,
    fin_pillow: /\/fin_pillow/,
    fin_partnering: /\/fin_partnering/,
    fin_instruments: /\/fin_instruments/,
    future_fin_plans: /\/future_fin_plans/,
    fin_independency: /\/fin_independency/,
    tax_strategy: /\/tax_strategy/,
    fin_responsibility: /\/fin_responsibility/,
}

module.exports = botIncomeMassages;